doubleToLongBits fix to enable haxe 3.2 be able to compile it to java and c#
Otherwise it yields this error:

C#:
src\HaxeNatives.cs(1007,24): error CS0266: Cannot implicitly convert type 'long' to 'int'. An explicit conversion exists (are you missing a cast?)
Compilation error
Native compilation failed

Java:
src\haxe\root\HaxeNatives.java:1707: error: incompatible types: possible lossy conversion from long to int
                        int __temp_stmt5 = 0xffffffffL;
                                           ^
2 errors